openapi: 3.1.0
info:
  version: 1.0.0
  title: Cavabanga app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of cavabanga app
tags:
  - name: Favorites
    description: Operations about favorites recipes.

servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
    api/recipes/favorites:
    get:
      $ref: ../swagger/paths/api/recipes/favorites/get.yaml
    api/recipes/favorites/{id}:
    post:
      $ref: ../swagger/paths/api/recipes/favorites/{id}/post.yaml
    delete:
      $ref: ../swagger/paths/api/recipes/favorites/{id}/delete.yaml
    get:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
